Revels/Auth/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'auth'
urlpatterns = [
    url(r'^signup',views.SignUp.as_view(),name='signup'),
    url(r'^signin',views.SignIn.as_view(),name='signin'),
    url(r'^signout',views.SignOut,name='signout'),
    url(r'^profile',views.Profile,name='profile'),
    url(r'^',views.Home.as_view(),name='home'),
]

Revels/Frontend/urls.py
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns=[
    url(r'^$',views.index,name="index"),
    url(r'^videos/(?P<video_id>[^/]+)/$',views.viewVideo,name="viewVideo"),
    url(r'^categories/(?P<catid>[^/]+)/$',views.catvideo,name="catvideo"),
    url(r'^upload/$',views.upload,name="upload"),
    url(r'^channel/(?P<chid>[^/]+)/$',views.getChannel,name='getChannel'),
    url(r'^playlist/(?P<plid>[^/]+)/$',views.getPlaylist,name='getPlaylist'),
    url(r'^create_channel/$',views.createChannel, name='createChannel'),
    url(r'^create_playlist/(?P<chid>[^/]+)$',views.createPlaylist,name='createPlaylist'),
    url(r'^create_comment/(?P<video_id>[^/]+)/$',views.createComment,name="create_comment"),
    url(r'^likes/(?P<video_id>[^/]+)/$',views.likes,name="likes"),
    url(r'^addpl/(?P<vid>[^/]+)/$',views.addtoplaylist,name='addtoplaylist'),
    url(r'^users/(?P<usr>[^/]+)/$',views.getUserDetails,name='userProfile'),
    url(r'^removepl/(?P<plid>[^/]+)/(?P<vid>[^/]+)/$',views.removeVidPl,name='removeVidPl'),
    url(r'^deletepl/(?P<plid>[^/]+)/$',views.deletePlaylist,name='deletePlaylist'),
    url(r'^deletech/(?P<chid>[^/]+)/$',views.deleteChannel,name='deleteChannel'),
    url(r'deletevid/(?P<vid>[^/]+)/$',views.deleteVid,name='deleteVid'),
    url(r'^search/$',views.search,name="search"),
    url(r'^tagSearch/(?P<tag>.*)/$',views.tagSearch,name="tagSearch"),
    url(r'^subscribe/(?P<chid>[^/]+)/$',views.subscribe,name='subscribe'),
]

Revels/Revels/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^',include('Frontend.urls')),
    url(r'^auth/',include('Auth.urls')),
]

Revels/Frontend/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render,redirect
from ORM.dbconnect import Connector
from ORM.video import Video
from ORM.category import Category
from ORM.user import User
from ORM.channel import Channel
from ORM.tag import Tag
from ORM.playlist import Playlist
from ORM.comment import Comment
from ORM.profile import Profile
from ORM.tag import Tag
from ORM.relations import Relationships
from ORM.sessions import SessionsManager

sess=SessionsManager()
con=Connector()
cat=Category()
tag=Tag()
vid=Video()

def trimVidDesc(s):
    return (' '.join(s.split(' ')[:35])) + "..."

def index(req):
    return render(req,'Frontend/index.html',{"category":cat.getall()})

def catvideo(req,catid):
    data=cat.get_CatVideos(catid)
    return render(req,'Frontend/category.html',{"data": data})

def upload(req):
    uid=sess.checkSession(req)
    catlist=cat.getall()
    if uid!=None :
        if req.method=='GET':
            return render(req,'Frontend/upload.html',{'category':catlist})
        elif req.method=='POST':
            data={
                'title': req.POST['title'].strip(),
                'descr':req.POST['descr'].strip(),
                'url': req.POST['url'].strip().replace("youtu.be","www.youtube.com/embed"),
                'tags': req.POST['tags'].strip(),
                'user_id': uid[0]['user_id'],
                'vidcatlist':req.POST.getlist('box')
            }
            vid.insert(data)
            res=vid.get_vid_id(data)
            video_id = res[0]['video_id']
            print(video_id)
            for catid in data['vidcatlist']:
                con.modify("""
                    INSERT INTO Vid_Cat(video_id,cat_id)
                    VALUES(%s,%s);
                """,video_id,int(catid))

            tag.insertTags(data['tags'],video_id)
            return render(req,'Frontend/upload.html',{'category':catlist,'msg':"Uploaded Sucessfully"})
    else:
        return redirect('auth:signin')

def createChannel(req):
    uid=sess.checkSession(req)
    if uid!=None:
        if req.method=='GET':
            return render(req,'Frontend/createchannel.html',{'id': uid[0]['user_id']})
        elif req.method=='POST':
            data={
                'name': req.POST['name'].strip(),
                'descr':req.POST['descr'].strip(),
                'defpl':req.POST['defpl'].strip(),
            }
            chid=len(con.query("SELECT channel_id FROM Channel;"))+1
            con.modify("""
                INSERT INTO Channel(name,description,user_id)
                VALUES(%s,%s,%s);
            """,data['name'],data['descr'],uid[0]['user_id'])
            con.modify("""
                INSERT INTO Playlist(name,channel_id)
                VALUES(%s,%s);
            """,data['defpl'],chid)
            return render(req,'Frontend/createchannel.html',{'id': uid[0]['user_id'],'msg':"Channel Successfully created !!"})
    else:
        return redirect('auth:signin')

def getChannel(req,chid):
    showdel=False
    uid=sess.checkSession(req)
    pllist=con.query("""SELECT * FROM Playlist WHERE channel_id=%s;""",int(chid))
    ch=con.query("""SELECT * FROM Channel WHERE channel_id=%s;""",int(chid))
    subs=False
    if len(ch)!=0:
        if uid!=None:
            if ch[0]['user_id']==uid[0]['user_id']:
                showdel=True
            sublist=con.query("""SELECT * FROM Subscription WHERE user_id=%s AND channel_id=%s;""",uid[0]['user_id'],chid)
            if len(sublist)==1:
                subs=True
            else:
                subs=False
        return render(req,'Frontend/channelpage.html',{'pllist':pllist,'ch':ch,'showdel':showdel,'subs':subs})
    else:
        return HttpResponse("<h4>Page not found.</h4>")

def getPlaylist(req,plid):
    showdel=False
    uid=sess.checkSession(req)
    pl=con.query("""SELECT Playlist.*,Channel.user_id
        FROM Playlist,Channel
        WHERE Playlist.channel_id=Channel.channel_id AND playlist_id=%s;""",plid)
    vidlist=con.query("""SELECT Video.video_id,Video.title
            FROM Playlist NATURAL JOIN Pl_Vid NATURAL JOIN Video
            WHERE Playlist.playlist_id=%s;""",plid)
    if len(pl)!=0:
        if uid!=None:
            if pl[0]['user_id']==uid[0]['user_id']:
                showdel=True
        if len(vidlist)==0:
            return render(req,'Frontend/playlistpage.html',{'msg':"No Videos",'pl':pl,'showdel':showdel})
        else:
            return render(req,'Frontend/playlistpage.html',{'vidlist':vidlist,'pl':pl,'showdel':showdel})
    else:
        return HttpResponse("<h4>Page not found.</h4>")

def createPlaylist(req,chid):
    uid=sess.checkSession(req)
    if uid!=None:
        ch=con.query("SELECT channel_id,name FROM Channel WHERE channel_id=%s AND user_id=%s",int(chid),int(uid[0]['user_id']))
        if ch == None:
            return redirect('/')
        else:
            if req.method=='GET':
                return render(req,'Frontend/createplaylist.html',{'ch':ch})
            elif req.method=='POST':
                con.modify("""
                    INSERT INTO Playlist(name,channel_id)
                    VALUES(%s,%s);
                """,req.POST['name'].strip(),ch[0]['channel_id'])
                return render(req,'Frontend/createplaylist.html',{'ch':ch,'msg':"Playlist Successfully created !!"})
    else:
        return redirect('auth:signin')

def viewVideo(req,video_id):
    uid=sess.checkSession(req)
    if uid==None:
        uid=0
    else:
        uid=uid[0]['user_id']
    video = con.query("SELECT * FROM Video NATURAL JOIN User_Profile WHERE video_id=%s",int(video_id))
    tags = con.query("SELECT * FROM Tag WHERE video_id=%s",int(video_id))
    comm = con.query("SELECT * FROM  User_Profile NATURAL JOIN Comment where Comment.video_id = %s", video[0]['video_id'])
    likes = con.query("SELECT COUNT(*) as c FROM `Like` WHERE video_id = %s",video[0]['video_id'])
    if req.method=='GET':
        var = {
            'video' : video[0],
            'comments' : comm,
            'tags' : tags,
            'likes' : likes[0]['c'],
            'liked' : vid.get_like(video[0]['video_id'],uid)
        }
        return render(req,'Frontend/video.html',var)

def createComment(req,video_id):
    if req.method=='POST':
        vid = con.query("SELECT * FROM Video NATURAL JOIN User_Profile WHERE video_id=%s",int(video_id))
        uid=sess.checkSession(req)
        if uid!=None:
            comm = req.POST['comment'].strip()
            con.modify("""
                INSERT INTO Comment(text, timestamp, video_id, user_id) VALUES (%s,CURRENT_TIMESTAMP(),%s,%s)
            """, comm, vid[0]['video_id'],uid[0]['user_id'])
            comm = con.query("SELECT * FROM  User_Profile NATURAL JOIN Comment where Comment.video_id = %s", vid[0]['video_id'])
            var = {
                'video' : vid[0],
                'comments' : comm,
            }
            return render(req,'Frontend/video.html',var)
        else:
            return redirect('auth:signin')

def likes(req,video_id):
    uid=sess.checkSession(req)
    if uid!=None :
        if req.method=='GET':
            pass
        elif req.method=='POST':
            if 'like' in req.POST :
                con.modify("""
                    INSERT INTO `Like`(video_id,user_id) VALUES (%s,%s)
                """,int(video_id),int(uid[0]['user_id']))
            elif 'unlike' in req.POST :
                con.modify("""
                    DELETE FROM `Like` WHERE user_id = %s
                """,int(uid[0]['user_id']))
            return redirect('viewVideo',video_id)
    else :
        return redirect('auth:signin')

def addtoplaylist(req,vid):
    uid=sess.checkSession(req)
    if uid!=None :
        if req.method=='GET':
            data=con.query("""
                SELECT channel_id,name AS chname FROM Channel
                WHERE user_id=%s ORDER BY channel_id;
            """,uid[0]['user_id'])
            for item in data:
                item['playlists']=con.query("""
                    SELECT playlist_id,name AS plname FROM Playlist
                    WHERE channel_id=%s;
                """,item['channel_id'])
            return render(req,'Frontend/addtoplaylist.html',{'data':data,'vid':vid})
        elif req.method=='POST':
            plids=req.POST.getlist('box')
            for item in plids:
                con.modify("""
                    INSERT INTO Pl_Vid
                    VALUES(%s,%s);
                """,vid,int(item))
            return redirect('viewVideo',vid)
    else :
        return redirect('auth:signin')

def removeVidPl(req,plid,vid):
    uid=sess.checkSession(req)
    pluser=con.query("""SELECT user_id FROM Playlist,Channel
            WHERE Playlist.channel_id=Channel.channel_id
            AND playlist_id=%s;""",plid)
    if uid!=None:
        if uid[0]['user_id']==pluser[0]['user_id']:
            con.modify("""DELETE FROM Pl_Vid
                WHERE video_id=%s AND playlist_id=%s;
                """,vid,plid)
        return redirect('getPlaylist',plid)
    else :
        return redirect('auth:signin')

def deletePlaylist(req,plid):
    uid=sess.checkSession(req)
    pluser=con.query("""SELECT Channel.channel_id,user_id FROM Playlist,Channel
            WHERE Playlist.channel_id=Channel.channel_id
            AND playlist_id=%s;""",plid)
    chid=pluser[0]['channel_id']
    if uid!=None:
        if uid[0]['user_id']==pluser[0]['user_id']:
            con.modify("""DELETE FROM Playlist
                WHERE playlist_id=%s;
                """,plid)
        return redirect('getChannel',chid)
    else :
        return redirect('auth:signin')

def deleteChannel(req,chid):
    uid=sess.checkSession(req)
    ch=con.query("""SELECT * FROM Channel
            WHERE channel_id=%s;""",chid)
    if uid!=None:
        if uid[0]['user_id']==ch[0]['user_id']:
            con.modify("""DELETE FROM Channel

Revels/Frontend/templates/Frontend/addtoplaylist.html
{% extends 'layouts/base.html' %}
{% block title %}
    Add To Playlist...
{% endblock title %}
{% block body %}
    <form action="{% url 'addtoplaylist' vid %}" method="post" class="container text-center" style="margin: auto; margin-top: 5em;">
        {% csrf_token %}
        <ol class="list-group">
            {% for item in data %}
                <li class=" list-group-item">
                    <div class="form-group">
                    <h3>{{ item.chname }}</h3>
                {% for pl in item.playlists %}
                <label class="form-check-label">
                    <input type="checkbox" class="form-check-input" name="box" value="{{ pl.playlist_id }}">{{ pl.plname }}<br>
                </label>
                {% endfor %}
                    </div>
                </li>
            {% endfor %}    
        </ol>
        
        <br></btr><input type="submit" value="Add" class="btn btn-primary">
    </form>
{% endblock body %}
    
    

Revels/Frontend/templates/Frontend/category.html
{% extends 'layouts/base.html' %}

{% block title %}
    {{ data.0.text }}
{% endblock title %}

{% block body %}
    <div class="col col-lg-10 text-center" style="margin:auto; margin-top:3em;">
        <ul class="list-group" >
        {% for item in data %}
            <li>
              <a class="list-group-item" href="{% url 'viewVideo' item.video_id %}">
                  <h5><b>{{item.title}}</b></h5>
                  <h6>{{item.descr}}</h6>
              </a>
            </li>
        {% endfor %}
        </ul>
    </div>

{% endblock body %}

Revels/Frontend/templates/Frontend/channelpage.html
{% extends 'layouts/base.html' %}

{% block title %}
    {{ ch.0.name }}
{% endblock title %}

{% block body %}
<div class="col col-lg-8 text-center" style="margin: auto; margin-top: 1em;">
    <h2>{{ ch.0.name }}</h2>
    <h4>{{ ch.0.description }}</h4>
    <br>
    <ul class="list-group">
        {% for pl in pllist %}
            <li><a href="{% url 'getPlaylist' pl.playlist_id %}" class="list-group-item">{{ pl.name }}</a></li>
        {% endfor %}        
    </ul>        
    <br>
    {% if showdel == True %}
        <form action="{% url 'createPlaylist' ch.0.channel_id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Create Playlist" class="btn btn-primary">
        </form>
        <br>
        <form action="{% url 'deleteChannel' ch.0.channel_id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete Channel" class="btn btn-primary">
        </form>
        <br>
    {% else %}
        <form action="{% url 'subscribe' ch.0.channel_id %}" method="post">
            {% csrf_token %}
            {% if subs == True %}
                <input type="submit" name="subscribe" value="Unsubscribe" class="btn btn-primary">
            {% else %}
                <input type="submit" name="subscribe" value="Subscribe" class="btn btn-primary">
            {% endif %}
        </form>
    {% endif %}
</div>
{% endblock body %}
    

Revels/Frontend/templates/Frontend/createchannel.html
{% extends 'layouts/base.html' %}


{% block title %}
    Create Channel
{% endblock title %}
    

{% block body %}
    <form action="{% url 'createChannel' %}" method="post" class="col col-lg-4 text-center" style="margin: auto; margin-top: 5em;">
        {% csrf_token %}
        <h3>Create Channel:</h3><br>
         <div class="form-group">
          <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" placeholder="Enter Channel Name">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" id="descr" name="descr" aria-describedby="descrHelp" placeholder="Enter Description">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" id="defpl" name="defpl" aria-describedby="defplHelp" placeholder="Default Playlist Name:">
        </div>
        <input type="submit" name="submit" value="Create" class="btn btn-primary"><br>    
    </form><br>
    {{ msg }}<br>
    <a href="{% url 'userProfile' id %}"  class="btn btn-secondary" style="margin: 0.25em">Back ...</a>
{% endblock body %}
    

Revels/Frontend/templates/Frontend/createplaylist.html
{% extends 'layouts/base.html' %}


{% block title %}
    {{ ch.0.name }}
{% endblock title %}
    

{% block body %}
    <form action="{% url 'createPlaylist' ch.0.channel_id %}" method="post" class="col col-lg-4 text-center" style="margin: auto; margin-top: 5em;">
        {% csrf_token %}
        <h3>Create Playlist:</h3><br>
        <div class="form-group">
          <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" placeholder="Enter Playlist Name">
        </div>
        <input type="submit" name="submit" value="Create" class="btn btn-primary"><br>      
    </form><br>
    {{ msg }}<br>
    <a href="{% url 'getChannel' ch.0.channel_id %}"  class="btn btn-secondary" style="margin: 0.25em">Go To Your Channel...</a>
{% endblock body %}
    

Revels/Frontend/templates/Frontend/index.html
{% extends 'layouts/base.html' %} {% block title %} Revels {% endblock title %} {% block body %}
<div class="container" style=" margin: auto; margin-top: 3em;margin-bottom: 3em;">
    <ul class="list-group">
        {% for item in category %}
        <li>
            <a class="list-group-item" href="{% url 'catvideo' item.cat_id %}">{{ item.text }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock body %}

Revels/Frontend/templates/Frontend/playlistpage.html
{% extends 'layouts/base.html' %} {% block title %} {{ pl.0.name }} {% endblock title %} {% block body %}
<div class="col col-lg-8 text-center" style="margin: auto; margin-top: 1em;">
    <h4>{{ pl.0.name }}</h4>
    <br> {{ msg }}
    <ol class="list-group">
        {% for item in vidlist %}
        <li class="row">
            <a href="{% url 'viewVideo' item.video_id %}" class=" list-group-item col col-lg-10">
                {{ item.title }}</a> {% if showdel == True %}
            <form action="{% url 'removeVidPl' plid=pl.0.playlist_id vid=item.video_id %}" class="col col-lg-2" method="post" style="margin-top: 0.25em">
                {% csrf_token %}
                <input type="submit" value="X" class="btn btn-danger">
            </form>
            {% endif %}

        </li>
        {% endfor %}
    </ol>
    <br> {% if showdel == True %}
    <form action="{% url 'deletePlaylist' pl.0.playlist_id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete Playlist" class="btn btn-danger">
    </form>
    {% endif %}
</div>
{% endblock body %}

Revels/Frontend/templates/Frontend/search.html
{% extends 'layouts/base.html' %} {% block title %} search {% endblock title %} {% block body %}

<form method="POST" action="{% url 'search' %}" class="row col-lg-10" style="margin:auto; margin-top: 2em ">
    {% csrf_token %}
    <input name="query" type="text" value="" class="col-lg-12 row" style="margin: 0.25em" />
    <select name="cat" class="form-control" style="width: 10em;margin: 0.25em" class="col col-lg-2">
        <option value="Videos">Videos</option>
        <option value="Categories">Categories</option>
        <option value="Channels">Channels</option>
        <option value="Playlists">Playlists</option>
        <option value="Users">Users</option>
    </select>
    <input name="" type="submit" class="btn btn-secondary" value="Search" class="col col-lg-1" style="margin: 0.25em">

</form>
<br>
<div class="container" style="margin-bottom: 5em;">
    {% if result %} {% if cat == "Categories" %}
    <h3 class="text-center">Categories</h3>
    <ul class="list-group">

        {% for res in result %}
        <a class="list-group-item" href="{% url 'catvideo' res.cat_id %}">
            <h4>{{res.text}}</h4>
        </a>
        {% empty %} No Videos Found {% endfor %} {% endif %} {% if cat == "Channels" %}
        <h3 class="text-center">Channels</h3>
        {% for res in result %}
        <a class="list-group-item" href="{% url 'getChannel' res.channel_id %}">
            <h5><b>{{res.name}}</b></h4>
                <h6>{{res.description}}</h4>
        </a>
        {% empty %} No Videos Found {% endfor %} {% endif %} {% if cat == "Playlists" %}
        <h3 class="text-center">Playlists</h3>
        {% for res in result %}
        <a class="list-group-item" href="{% url 'getPlaylist' res.playlist_id %}">
            <h5>{{res.name}}</h5>
        </a>
        {% empty %} No Videos Found {% endfor %} {% endif %} {% if cat == "Videos" %}
        <h3 class="text-center">Videos</h3>
        {% for res in result %}
        <a class="list-group-item" href="{% url 'viewVideo' res.video_id %}">
            <h5><b>{{res.title}}</b></h5>
            <h6>{{res.descr}}</h6>
        </a>
        {% empty %} No Videos Found {% endfor %} {% endif %} {% if cat == "Users" %}
        <h3 class="text-center">Users</h3>
        {% for res in result %}
        <a class="row list-group-item" href="{% url 'userProfile' res.user_id %}">
            <article class="">
                <small>{{res.username}}</small>
                <h4>{{res.firstname}} {{res.lastname}}</h4>
            </article>
        </a>
        {% empty %} No Videos Found {% endfor %} {% endif %} {% endif %}
</div>
{% endblock body %}

Revels/Frontend/templates/Frontend/upload.html
{% extends 'layouts/base.html' %} {% block title %} Upload Video {% endblock title %} {% block body %}
<form action="{% url 'upload' %}" method="post" class="col col-lg-8 text-center" style="margin: auto; margin-top: 1em;">
    {% csrf_token %}
    <h3>Upload Video</h3><br>
    <div class="form-group">
        <input type="text" class="form-control" id="title" name="title" aria-describedby="titleHelp" placeholder="Enter Video Title">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="url" name="url" aria-describedby="urlHelp" placeholder="Enter Video URL">
    </div>
    <div class="form-group">
        <textarea class="form-control" id="descr" name="descr" rows="4" placeholder="Enter Video description"></textarea>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" id="tags" name="tags" aria-describedby="tagsHelp" placeholder="Enter Tags seperated by comma">
    </div>

    <label for="category" required><b><h3>Category: </h3></b></label><br> {% for cat in category %}
    <div class="form-check form-check-inline">
        <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="box" value="{{ cat.cat_id }}"> <b>{{ cat.text }}</b>
              </label>
    </div>
    {% endfor %}
    <br><br>
    <input type="submit" name="submit" value="Upload" class="btn btn-primary"><br>
</form><br> {{ msg }} {% endblock body %}

Revels/Frontend/templates/Frontend/user.html
{% extends 'layouts/base.html' %} {% block title %} {{user.username}} {% endblock title %} {% block body %}
<div class="col col-lg-10" style="margin: auto; margin-top: 3em;">
    <section class="row">
        <i class="fa fa-user-circle col col-lg-3" aria-hidden="true" style="font-size: 7.5em;"></i>
        <article class=" col col-lg-3">
            <h1>{{user.username}}</h1>
            <h4>{{user.firstname}} {{user.lastname}}</h4>
        </article>
        <hr>
    </section>
    <br>
    <div class="text-center">
        <h3><b>Channels</b></h3>
        <ul class="list-group">
            {% for channel in channels %}
            <li>
                <a href="{% url 'getChannel' channel.channel_id %}" class="list-group-item">
                    <h4>{{channel.name}}</h4>
                    <h6>{{channel.description}}</h6>
                </a>
            </li>
            {% empty %}
            <h4 class="text-center" style="width:100%;">No Channels</h4>{% endfor %}
        </ul>
        <br><br>
        <h3><b>Videos</b></h3><br>
        <div class="row text-center">
            {% for video in videos %}
            <div class="col-lg-4" style="padding:0.5em">
                <div class="card">
                    <div class="card-block" style="padding:1em">
                        <h4 class="card-title">
                            <a href="{% url 'viewVideo' video.video_id %}">{{video.title}}</a></h4>
                        <p class=" card-text ">{{video.descr}}</p>
                        {% if owner == True %}
                        <form action="{% url 'deleteVid' video.video_id %} " method="post " style="margin: 1em ">
                            {% csrf_token %}
                            <input type="submit" value="Remove " class="btn btn-danger ">
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            <br> {% empty %}
            <h5 class="text-center" style="width:100%;"> No Uploaded Videos </h5>{% endfor %}
        </div>
        <br>
        <h3><b>Subscribed Channels</b></h3>
        <ul class="list-group ">
            {% for channel in subchannel %}
            <li>
                <a href="{% url 'getChannel' channel.channel_id %} " class="list-group-item ">
                    <h4>{{channel.name}}</h4>
                    <h6>{{channel.description}}</h6>
                </a>
            </li>
            {% empty %}
            <h4 class="text-center" style="width:100%;"> No Subsciptions </h4>{% endfor %}
        </ul>
        <br><br>
        <section class="row " style="margin-bottom: 1em; ">
            {% if owner == True %}
            <form class="col col-lg-4 " action="{% url 'upload'%} " method="get ">
                {% csrf_token %}
                <input type="submit" value="Upload Videos" class="btn btn-primary ">
            </form>
            <a class="col col-lg-4 btn btn-danger" href="{% url 'auth:signout' %} ">Sign Out</a>
            <form class="col col-lg-4 " action="{% url 'createChannel'%} " method="get ">
                {% csrf_token %}
                <input type="submit" value="New Channel " class="btn btn-primary ">
            </form>
            {% endif %}
        </section>

    </div>
</div>
{% endblock body %}

Revels/Frontend/templates/Frontend/video.html
{% extends 'layouts/base.html' %} {% block title %} {{ video.title }} {% endblock title %} {% block body %}
<div class="container" style="margin: auto; margin-top: 3em ">
    <h2 class="text-center">{{ video.title }}</h2><br>
    <div class="text-center embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="{{ video.url }}" allowfullscreen></iframe>
    </div>
    <br>
    <ul class="list-inline">
        {% for tag in tags %}
        <a href="{% url 'tagSearch' tag.tag %}">
            <li class="badge badge-primary">{{tag.tag}}</li>
        </a>
        {% endfor %}
    </ul>
    <br>
    <h5><b>By <a href="{% url 'userProfile' video.user_id %}">{{ video.username }}</a></b></h5>
    <h6>{{ video.descr }}</h6>
    <br>

    <div class="row">

        <form class="col col-lg-1" action="{% url 'likes' video.video_id %}" method="post">
            {% csrf_token %}
            <h5>{{ likes }} Likes</h5>
            {% if liked == False %}
            <input type="submit" class="btn btn-success" name="like" value="like"> {% else %}
            <input type="submit" class="btn btn-danger" name="unlike" value="unlike"> {% endif %}
        </form>
        <section class="col col-lg-10"></section>
        <a class="col col-lg-1" href="{% url 'addtoplaylist' video.video_id %}"><button class="btn btn-dark">Add To Playlist</button></a><br><br>
    </div>
    <br>
    <form class="col col-lg-10" action="{% url 'create_comment' video.video_id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="comment"><b>Comment</b></label>
            <small id="commentHelp" class="form-text text-muted">Please leave your comments below ...</small>
            <input type="comment" class="form-control" id="comment" name="comment" aria-describedby="commentHelp" placeholder="Enter Comment">
        </div>
        <input type="submit" class="btn btn-primary" value="Add comment">
    </form>
    <br>
    <ul class="list-group" style="margin-bottom: 1em;">
        {% for comment in comments %}
        <li class="list-group-item">
            <a href="{% url 'userProfile' comment.user_id %}"><small><b>{{ comment.username }}</b></small></a>
            <h5>{{ comment.text }}</h5>
        </li>

        {% endfor %}
    </ul>

</div>
{% endblock body %}